language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
branches:
  only:
    - main
before_script:
  - npm install -g @angular/cli
  - npm install primeng --save
  - npm install primeicons --save
script:
  - ng lint
  - ng build
